<a href="https://colab.research.google.com/github/mjkimcs/portfolio/blob/main/2_17_%ED%85%8D%EC%8A%A4%ED%8A%B8%EB%A7%88%EC%9D%B4%EB%8B%9D_%EC%97%B0%EA%B4%80%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.6/dist-packages (0.14.0)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.6/dist-packages (from mlxtend) (1.19.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from mlxtend) (53.0.0)
Requirement already satisfied: matplotlib>=1.5.1 in /usr/local/lib/python3.6/dist-packages (from mlxtend) (3.2.2)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.6/dist-packages (from mlxtend) (0.22.2.post1)
Requirement already satisfied: pandas>=0.17.1 in /usr/local/lib/python3.6/dist-packages (from mlxtend) (1.1.5)
Requirement already satisfied: scipy>=0.17 in /usr/local/lib/python3.6/dist-packages (from mlxtend) (1.4.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.5.1->mlxtend) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.5.1->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.5.1->mlxtend) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib>=1.5.1->mlxtend) (2.8.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.6/dist-packages (from scikit-learn>=0.18->mlxtend) (1.0.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.17.1->mlxtend) (2018.9)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from cycler>=0.10->matplotlib>=1.5.1->mlxtend) (1.15.0)

In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [15]:
dataset = [
           ["사과", "치즈", "생수", "호두"],
           ["치즈", "고등어", "생수"],
           ["팥", "호두", "복숭아"],
           ["호두", "치즈", "팥"]
]
te = TransactionEncoder()
te_transform = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_transform, columns=te.columns_)
df

     고등어    복숭아     사과     생수     치즈      팥     호두
0  False  False   True   True   True  False   True
1   True  False  False   True   True  False  False
2  False   True  False  False  False   True   True
3  False  False  False  False   True   True   True

In [11]:
# 연관분석

df_apr = apriori(df, use_colnames=True)
print(df_apr)

# 팥과 호두를 같이 고른 사람은 4명 중에 2명 즉 50%
# 호두와 치즈의 연관성은 50% 이다.
# 팥과 호두를 같이 고른 사람이 100% 라면 팥과 호두는 서로 연관성이 아주 높은 것이라고 분석할 수 있음

   support  itemsets
0     0.50      (생수)
1     0.75      (치즈)
2     0.50       (팥)
3     0.75      (호두)
4     0.50  (생수, 치즈)
5     0.50  (호두, 치즈)
6     0.50   (팥, 호두)

In [13]:
!pip install konlpy

Collecting konlpy
  Downloading https://files.pythonhosted.org/packages/85/0e/f385566fec837c0b83f216b2da65db9997b35dd675e107752005b7d392b1/konlpy-0.5.2-py2.py3-none-any.whl (19.4MB)
     |████████████████████████████████| 19.4MB 1.5MB/s
Collecting beautifulsoup4==4.6.0
  Downloading https://files.pythonhosted.org/packages/9e/d4/10f46e5cfac773e22707237bfcd51bbffeaf0a576b0a847ec7ab15bd7ace/beautifulsoup4-4.6.0-py3-none-any.whl (86kB)
     |████████████████████████████████| 92kB 8.0MB/s
Collecting tweepy>=3.7.0
  Downloading https://files.pythonhosted.org/packages/67/c3/6bed87f3b1e5ed2f34bd58bf7978e308c86e255193916be76e5a5ce5dfca/tweepy-3.10.0-py2.py3-none-any.whl
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.6/dist-packages (from konlpy) (4.2.6)
Collecting JPype1>=0.7.0
  Downloading https://files.pythonhosted.org/packages/de/af/93f92b38ec1ff3091cd38982ed19cea2800fefb609b5801c41fc43c0781e/JPype1-1.2.1-cp36-cp36m-manylinux2010_x86_64.whl (457kB)
     |████████████████████████████████| 460kB 33.9MB/s
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.6/dist-packages (from konlpy) (1.19.5)
Collecting colorama
  Downloading https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
Requirement already satisfied: requests[socks]>=2.11.1 in /usr/local/lib/python3.6/dist-packages (from tweepy>=3.7.0->konlpy) (2.23.0)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from tweepy>=3.7.0->konlpy) (1.15.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.6/dist-packages (from tweepy>=3.7.0->konlpy) (1.3.0)
Requirement already satisfied: typing-extensions; python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from JPype1>=0.7.0->konlpy) (3.7.4.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests[socks]>=2.11.1->tweepy>=3.7.0->konlpy) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests[socks]>=2.11.1->tweepy>=3.7.0->konlpy) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests[socks]>=2.11.1->tweepy>=3.7.0->konlpy) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests[socks]>=2.11.1->tweepy>=3.7.0->konlpy) (3.0.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6; extra == "socks" in /usr/local/lib/python3.6/dist-packages (from requests[socks]>=2.11.1->tweepy>=3.7.0->konlpy) (1.7.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.6/dist-packages (from requests-oauthlib>=0.7.0->tweepy>=3.7.0->konlpy) (3.1.0)
Installing collected packages: beautifulsoup4, tweepy, JPype1, colorama, konlpy
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
  Found existing installation: tweepy 3.6.0
    Uninstalling tweepy-3.6.0:
      Successfully uninstalled tweepy-3.6.0
Successfully installed JPype1-1.2.1 beautifulsoup4-4.6.0 colorama-0.4.4 konlpy-0.5.2 tweepy-3.10.0

In [41]:
import urllib.request as req
from bs4 import BeautifulSoup
import urllib.parse as par
from konlpy.tag import Okt

okt = Okt()

keyword = "카이스트"
encoded = par.quote(keyword)
page_num = 1
dataset = [] # 여기 추가
while True:
  url = "https://news.joins.com/Search/JoongangNews?page={}&Keyword={}&SortType=New&SearchCategoryType=JoongangNews".format(page_num, encoded)
  code = req.urlopen(url)
  soup = BeautifulSoup(code, "html.parser")
  title = soup.select("h2.headline.mg > a")
  if len(title) == 0:
    break
  for i in title:
    print("제목: ", i.text)
    print("링크: ", i.attrs["href"])
    dataset.append(okt.nouns(i.text)) # nouns함수는 리스트형으로 반환
  page_num += 1
  if page_num == 3:
    break

dataset_cleansing = []
for data in dataset:
  data_cleansing = []
  for i in data:
    if len(i) != 1:
      data_cleansing.append(i)
  dataset_cleansing.append(data_cleansing)
  
print(dataset_cleansing)

te = TransactionEncoder()
te_transform = te.fit(dataset_cleansing).transform(dataset_cleansing)
df = pd.DataFrame(te_transform, columns=te.columns_)
df
df_apr = apriori(df, use_colnames=True, min_support=0.1) # apriori함수는 연관성이 0.5 이상인 것만 결과를 보여주기 때문에 min_support 옵션을 넣어줌
print(df_apr)

제목:  “내 PC 해킹하라” 시험 낸 괴짜 교수, KAIST 총장 됐다
링크:  https://news.joins.com/article/23995372
제목:  드라마 '카이스트' 괴짜 교수, 진짜 카이스트 총장 됐다
링크:  https://news.joins.com/article/23995009
제목:  [팩플] 배민·아자르·쿠팡 다음은?…글로벌 노리는 K유니콘 "저평가 뒤집을 기회"
링크:  https://news.joins.com/article/23994558
제목:  [트랜D] 재택 경제 시대의 스마트홈 플랫폼
링크:  https://news.joins.com/article/23992287
제목:  카이스트, '성추행' 전 서울대 교수 세미나 초청하려다 취소
링크:  https://news.joins.com/article/23991453
제목:  [단독]“선물로 에어팟프로”…대놓고 리스트 공개 232% 껑충
링크:  https://news.joins.com/article/23990516
제목:  백운규 영장기각에 민주당 “윤석열, 정치 수사 즉각 중단하라”
링크:  https://news.joins.com/article/23989379
제목:  신한울 폐기 안했는데, 산업부 문건엔 "백지화"…이랬던 탈원전
링크:  https://news.joins.com/article/23985631
제목:  [트랜D] 코로나19로 급부상한 메타버스 트렌드
링크:  https://news.joins.com/article/23983285
제목:  [다시 뛰는 대한민국] 신규 점포와 리뉴얼 통해 신성장동력 확보
링크:  https://news.joins.com/article/23981212
제목:  KTV '삼중수소' 방송에…KAIST 교수 “1g 나와도 죽어요” 발끈
링크:  https://news.joins.com/article/23977726
제목:  [단독] KAIST서 확진 1명 나왔다···접촉자 12명은 모두 음성
링크:  https://news.joins.com/article/23976511
제목:  "삼중수소도 결국 몸 밖으로 배출된다" 카이스트 교수 일침
링크:  https://news.joins.com/article/23973287
제목:  석사가 쟁쟁한 박사 다 제쳤다···'공학의 전당' 입성 택진이형
링크:  https://news.joins.com/article/23971922
제목:  과학기술정책연구원장에 문미옥 전 의원…'실세' 온다는데 과학계선 부정 기류
링크:  https://news.joins.com/article/23971494
제목:  마크롱의 한국계 최측근 “성평등, 모든 정책 필수요건으로”
링크:  https://news.joins.com/article/23970858
제목:  월성원전 의혹 감사원·檢 탓하는 與 "원전 마피아와 결탁했나"
링크:  https://news.joins.com/article/23969757
제목:  [단독] 이루다 만든 스캐터랩 대표 “이루다 논란, 오늘 입장 밝힌다”
링크:  https://news.joins.com/article/23967978
제목:  월성원전 지하수가 삼중수소에 오염?…"외부유출 증거 없어"
링크:  https://news.joins.com/article/23967895
제목:  [소년중앙] 인간형 로봇 휴보가 120~150㎝인 이유, 인간과 친해지기 위해서죠
링크:  https://news.joins.com/article/23967561
[['해킹', '시험', '괴짜', '교수', '총장'], ['드라마', '카이스트', '괴짜', '교수', '진짜', '카이스트', '총장'], ['배민', '아자르', '쿠팡', '다음', '글로벌', '유니콘', '평가', '기회'], ['트랜', '재택', '경제', '시대', '스마트홈', '플랫폼'], ['카이스트', '성추행', '서울대', '교수', '세미나', '초청', '취소'], ['단독', '선물', '에어팟', '프로', '리스트', '공개', '껑충'], ['운규', '영장', '기각', '민주당', '윤석열', '정치', '수사', '즉각', '중단'], ['한울', '폐기', '산업부', '문건', '백지', '원전'], ['트랜', '코로나', '급부', '메타', '버스', '트렌드'], ['다시', '대한민국', '신규', '점포', '리뉴얼', '통해', '성장동력', '확보'], ['삼중수소', '방송', '교수', '발끈'], ['단독', '확진', '접촉', '모두', '음성'], ['삼중수소', '배출', '카이스트', '교수', '일침'], ['석사', '쟁쟁', '박사', '공학', '전당', '입성', '택진', '이형'], ['과학기술', '정책', '연구원', '의원', '실세', '과학계', '부정', '기류'], ['마크', '한국', '최측근', '평등', '모든', '정책', '필수', '요건'], ['월성원전', '의혹', '감사원', '원전', '마피아', '결탁'], ['단독', '스캐터랩', '대표', '논란', '오늘', '입장'], ['월성원전', '지하수', '삼중수소', '오염', '외부', '유출', '증거'], ['소년', '중앙', '인간', '로봇', '휴보', '이유', '인간']]
    support      itemsets
0      0.10          (괴짜)
1      0.25          (교수)
2      0.15          (단독)
3      0.15        (삼중수소)
4      0.10          (원전)
5      0.10        (월성원전)
6      0.10          (정책)
7      0.10          (총장)
8      0.15        (카이스트)
9      0.10          (트랜)
10     0.10      (교수, 괴짜)
11     0.10      (괴짜, 총장)
12     0.10    (교수, 삼중수소)
13     0.10      (교수, 총장)
14     0.15    (교수, 카이스트)
15     0.10  (교수, 괴짜, 총장)

In [42]:
df_apr["length"] = df_apr["itemsets"].str.len()
df_apr

    support      itemsets  length
0      0.10          (괴짜)       1
1      0.25          (교수)       1
2      0.15          (단독)       1
3      0.15        (삼중수소)       1
4      0.10          (원전)       1
5      0.10        (월성원전)       1
6      0.10          (정책)       1
7      0.10          (총장)       1
8      0.15        (카이스트)       1
9      0.10          (트랜)       1
10     0.10      (교수, 괴짜)       2
11     0.10      (괴짜, 총장)       2
12     0.10    (교수, 삼중수소)       2
13     0.10      (교수, 총장)       2
14     0.15    (교수, 카이스트)       2
15     0.10  (교수, 괴짜, 총장)       3

In [43]:
df_result = df_apr[df_apr["length"] == 2]["itemsets"]
df_result

10      (교수, 괴짜)
11      (괴짜, 총장)
12    (교수, 삼중수소)
13      (교수, 총장)
14    (교수, 카이스트)
Name: itemsets, dtype: object

In [35]:
!pip install networkx

Requirement already satisfied: networkx in /usr/local/lib/python3.6/dist-packages (2.5)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.6/dist-packages (from networkx) (4.4.2)

In [36]:
def show_me_the_graph(df):
    import networkx as nx
    import numpy as np
    import matplotlib.pyplot as plt
    import matplotlib.font_manager as fm

    g = nx.Graph()
    g.add_edges_from(df)
    pr = nx.pagerank(g)
    nsize = np.array([v for v in pr.values()])
    nsize = 10000 * (nsize - min(nsize)) / (max(nsize) - min(nsize))
    pos = nx.kamada_kawai_layout(g)
    font_name = fm.FontProperties(fname="/content/NanumMyeongjoBold.ttf").get_name()
    plt.figure(figsize=(16, 12))
    plt.axis("off")
    nx.draw_networkx(g, font_family=font_name, font_size=16,
                     pos=pos, node_color=list(pr.values()), edge_color='.5', node_size=nsize,
                     alpha=0.7, cmap=plt.cm.Blues)
    plt.show()

In [37]:
import matplotlib.font_manager as fm
fm._rebuild()

In [ ]:
show_me_the_graph(df_result)

폰트 에러 발생 시,  
import matplotlib.font_manager as fm
fm._rebuild()